--- 

- include: redhat-main.yml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7' 

- include: debian-main.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '16'
